### ISSUE TITLE
node: command not found

### ISSUE THREAD

**Issue by MikeYermolayev** [unfold/heroku-buildpack-pnpm#1]
Hello :wave:

I'm trying to use buildpack and it works okay for build stage but the app itself fail to start. I get `node: command not found`

![image](https://user-images.githubusercontent.com/8783498/145735127-60b21089-fd13-4d18-b0fa-8f9782cd9393.png)

![image](https://user-images.githubusercontent.com/8783498/145735149-2ffca8f4-1736-41f9-9116-25f2795ac97c.png)

---
Procfile
```
web: node dist/server.js
```

Any ideas or workarounds? Thanks in advance

**Comment by hampusborgos** [comment]
Try adding `node@16~` as a dependency.

**Comment by hampusborgos** [comment]
This should be fixed now. :)
