### ISSUE TITLE
bin/compile: line 233: pnpm: command not found

### ISSUE THREAD

**Issue by tom-quiltt** [unfold/heroku-buildpack-pnpm#39]
**Describe the bug**
With the new version of buildpack, the script to respect `engines.pnpm` seems to break pnpm install.
https://github.com/unfold/heroku-buildpack-pnpm/blob/9a5caa934cceebc0f8c61b5c77fb41429630aeff/bin/compile#L225-L235

Seeing this in logs
```
2023-04-04 16:41:17        Downloading and installing pnpm... /tmp/codon/tmp/buildpacks/6850fdb5590ef7398f98be618d4e33eed777eadc/bin/compile: line 233: pnpm: command not found
```

Looks like the script didn't wait until the install complete and start calling `pnpm`.

**Comment by Turbo87** [comment]
FWIW we had the buildpack pinned to 76cf1fc and it also started showing the `pnpm: command not found` error mentioned above. it might be that something in the Heroku machines has changed that makes this not work anymore.

**Comment by mrabdibdi-anvil** [comment]
Hello !
seems to be an issue with unpkg

https://github.com/mjackson/unpkg/issues/361

Proposed fix: https://github.com/mjackson/unpkg/issues/358#issuecomment-1496263654
